name: Deploy to Cloud Run

on:
  workflow_dispatch:

env:
  PROJECT_ID: fiap-3soat-g53
  GAR_LOCATION: us-central1-docker.pkg.dev/fiap-3soat-g53/fiap3soatg53-gar
  SERVICE: helthmed-scheduling
  IMAGE: helthmed-scheduling
  REGION: us-central1
  TAG: 'latest'

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # NOTE: Alternative option - authentication via workload_identity_provider
      # - name: Google Auth
      #   id: auth
      #   uses: 'google-github-actions/auth@main'
      #   with:
      #     token_format: 'access_token'
      #     workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
      #     service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@main'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ env.GAR_LOCATION }}/${{ env.IMAGE }}:${{ env.TAG }}
          flags: --cpu=1 --timeout=1800 --cpu-throttling --concurrency=500 --memory=512Mi --min-instances=1 --max-instances=20 --port=8080 --ingress=all --allow-unauthenticated --set-secrets='DATABASE_PASSWORD=DATABASE_PASSWORD:latest,RABBIT_PASSWORD=RABBIT_PASSWORD:latest' --add-cloudsql-instances=fiap-3soat-g53:us-central1:fiap3soatg53-sql

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}